### ISSUE TITLE
Erros when evaluating the pre-trained model

### ISSUE THREAD

**Issue by geyuying** [lukashermann/hulc#1]
Thanks for your excellent work!

When I download the pre-trained model and evaluate it, the error occurs '`No module named 'hulc.models.decoders.action_decoder_gripper_cam_rnn'` when loading module 
'hulc.models.decoders.action_decoder_gripper_cam_rnn.ActionDecoderGripperCamRNN''.

It seems that  the current repo does not include **action_decoder_gripper_cam_rnn**.

**Comment by lukashermann** [comment]
Thank you for pointing this out, we did not adapt the pre-trained models after the last refactoring. Now it should work, you will have to pull the newest commit and download the checkpoints again.
