### ISSUE TITLE
Evaluate Pretrained Models - "No module named 'hulc.datasets'" 

### ISSUE THREAD

**Issue by RobertMcCarthy97** [lukashermann/hulc#11]
Hi,

I am trying to evaluate the provided pretrained models. I followed the hulc install instructions, but initially ran into this issue:

`Traceback (most recent call last):
  File "hulc/evaluation/evaluate_policy.py", line 10, in <module>
    from calvin_agent.evaluation.utils import get_default_model_and_env
ModuleNotFoundError: No module named 'calvin_agent'`

To resolve this I installed the [calvin repo](https://github.com/mees/calvin).

However, I am now getting the following error:
`ImportError: Encountered error: "No module named 'hulc.datasets'" when loading module 'hulc.datasets.hulc_data_module.HulcDataModule'`

It seems like the `hulc/datasets` folder no longer exists in this repository?

Any help is appreciated, thanks!

**Comment by RobertMcCarthy97** [comment]
I managed to get it working by rolling back to a previous commit:
`git checkout 0bbc52`

Then:
`python hulc/evaluation/evaluate_policy.py --dataset_path $HULC_ROOT/dataset/calvin_debug_dataset --train_folder $HULC_ROOT/checkpoints/HULC_D_D --checkpoint $HULC_ROOT/checkpoints/HULC_D_D/saved_models/HULC_D_D.ckpt --debug`

**Comment by lukashermann** [comment]
This was caused by us not updating the model weights after the last refactoring commit, we apologize for that.
We uploaded the new HULC_D_D checkpoint, so now it should also work on the newest commit!

- [ ] add calvin_agent to requirements

**Comment by RobertMcCarthy97** [comment]
`evaluate_policy.py` works fine now with the new HULC_D_D checkpoint, thanks for the help!

**Comment by RobertMcCarthy97** [comment]
Would it be possible to also upload the updated HULC_ABCD_D checkpoint?

I need the pretrained model to perform as well as possible, and I believe HULC_ABCD_D performs better than HULC_D_D (according to the paper).

**Comment by Will-Zhe** [comment]
> 是否也可以上传更新的 HULC_ABCD_D 检查点？
> 
> 我需要预训练模型尽可能地表现出色，而且我相信 HULC_ABCD_D 的表现优于 HULC_D_D（根据论文）。

Hi there! I had the same issue while testing the pre-trained model HULC_ABC_D. Has this problem been resolved yet?

**Comment by Wang-Ji-Zhe** [comment]
Hi there! I had the same issue while testing the pre-trained model HULC_ABC_D. Has this problem been resolved yet?
