### ISSUE TITLE
Which language model you used to get the "lang_paraphrase-MiniLM-L3-v2" embedding.

### ISSUE THREAD

**Issue by hk-zh** [lukashermann/hulc#12]
I am trying to interactively test the learned policy by giving the agent an arbitrary command, not the predefined task description.  I saw the file `hulc/evaluation/test_policy_interactive.py` but I found it initialize the language encoder SBert("mpnet"). Could I ask which language model you used (maybe pytorch code) to get the  "lang_paraphrase-MiniLM-L3-v2" embedding you used for training?

**Comment by mees** [comment]
Hi there,
this is the language model use https://huggingface.co/sentence-transformers/paraphrase-MiniLM-L3-v2
Here is an example of how to use it:
https://www.sbert.net/docs/quickstart.html
