### ISSUE TITLE
Error while running trainning.py 

### ISSUE THREAD

**Issue by lzhhh93** [lukashermann/hulc#14]
Hi everyone,

I am trying to run the trainning.py for debug dataset without using the pretrained model. Now I stuck at this TypeError:

!['calvin_env _file_' is 'None'](https://github.com/lukashermann/hulc/assets/38736831/d4dcbba0-07dd-4792-a8ac-27618e874148)

Since I am not sure about what 'calvin_env._file_' here refer to, I am confused.

Thanks for any tipps in advance.

**Comment by aopolin-lv** [comment]
Hello, I met this problem, too. Could you give me some advice to solve this problem?

**Comment by lzhhh93** [comment]
> Hello, I met this problem, too. Could you give me some advice to solve this problem?

Hi, a quick way to resolve it would be: 

in line 72 above, replace the argument for the Path() function with the absolute path of the "calvin_env" like this:      
   `log.info(f"Using calvin_env with commit {get_git_commit_hash(Path('your/path/to/calvin_env'))}.")`
